type: pipeline_definition
name: Testing SPS PR Pipeline
description: "Runs a set of compliance status checks for the gkertasef/ci.docker app repo."
triggers:
- type: github
  keyword: "!gk-pr"
  triggerName: "gkSPSViaPR"